name: test

on:
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      
      - name: test
        run : go test ./...


